### ISSUE TITLE
option disable createTenant when using the offline scan option

### ISSUE THREAD

**Issue by jsa2** [armosec/kubescape#397]
It seems, that even in offline scan mode the tooling tries to contact the api.armo.cloud and certain AWS endpoint. I am using WSL2. Obviously it could also be possible, that some of the CMD arguments are not working properly?

```sh
kubescape scan framework mitre  --format json --output results.json --use-artifacts-from kubeScapeControls --keep-local --use-from ~/.kubescape/config.json
```
![image](https://user-images.githubusercontent.com/58001986/154816136-71795f2a-2eb5-4c18-96be-56b3d6b6eebb.png)

**Comment by dwertent** [comment]
Hi @jsa2, I noticed this behavior a few days ago and [fixed it](https://github.com/armosec/kubescape/pull/392).
It should be fixed next release :)

**Comment by jsa2** [comment]
Hi dear kubesec maintainers, to me it seems, that it still tries to create new tenant.

These are the options are I am using 

```
Your current version is: v2.0.148

kubescape scan framework mitre  --format json --output results.json --use-artifacts-from kubeScapeControls --exclude-namespaces kube-system,kube-public,default

``` 
With the aforementioned settings I still get the following POST attempt in the logs and wireshark (I've set the names to localhost in offline scans to not get the timeout delay)

`` Post "https://report.armo.cloud/k8s/v2/postureReport?clusterName=""n&customerGUID=""4&reportGUID="": dial tcp 127.0.1.1:443: connect: connection refused: ``

**Comment by dwertent** [comment]
@jsa2 It is possible the previous version left some cached data.
Can you please run `kubescape config delete` before running the `scan` command? 
Please keep me updated on this :)

**Comment by jsa2** [comment]
This is from fresh Ubuntu install. (Appreciate your quick support on this again :) )

The cmd arguments are as follow

```
 kubescape scan framework mitre  --format json --output results.json --use-artifacts-from kubeScapeControls --exclude-namespaces kube-system,kube-public,default
```
![image](https://user-images.githubusercontent.com/58001986/154901518-08a4f268-6315-495d-a392-e19183a95420.png)

**Comment by dwertent** [comment]
Thank you @jsa2  for reporting this issue.
I'm trying to understand what is going wrong.

What do you see when you run:
1. `kubectl describe configmap kubescape`
2. `cat ~/.kubescape/config.json`
3. `kubescape config view`

If there is an accountID, please replace the account by `xxx` before posting here

**Comment by jsa2** [comment]
Hi,

Pasted screencap here

![image](https://user-images.githubusercontent.com/58001986/154904870-be68f8e5-9743-4969-a228-bebe1b5324d0.png)

**Comment by dwertent** [comment]
Well then there is cache in the cluster (configmap).
Run `kubescape config delete` and it should be ok

**Comment by jsa2** [comment]
Ok, I am just wondering where the cache is coming from, as this was fresh installation. Perhaps it looks, if the test cluster I had is on an existing account that was submitted and populates the cache on installation?

**Comment by jsa2** [comment]
Anyway, I shall test now and report back

**Comment by jsa2** [comment]
Thx, that seemed to solve it. Still seems to look for something related to the version. Ill add something to the startup script.

func NewVersionCheckHandler() *VersionCheckHandler {
	return &VersionCheckHandler{
		versionURL: "https://us-central1-elated-pottery-310110.cloudfunctions.net/ksgf1v1",
	}
}
![image](https://user-images.githubusercontent.com/58001986/154906388-12dc7e76-37f1-40df-8b8e-91177c3771e9.png)

**Comment by dwertent** [comment]
Yes, once you submit the cluster results, the cache is stored in the configMap so a single cluster will report results to the same account and not different accounts.
If you no longer wish to report results you can scan with the `--keep-local` flag or remove the cache with `config delete`.

Regarding the version check -> Kubescape checks if there is a new version released. You can disable the version check by setting an environment variables as following: `KUBESCAPE_SKIP_UPDATE_CHECK=true`
